<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search_e-font-icon-svg-container</name>
   <tag></tag>
   <elementGuidId>b7369ce5-74fe-428e-83d5-17b0ab3ee05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.e-font-icon-svg-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>72d5eed3-a7f1-4348-816d-ce421c61596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-font-icon-svg-container</value>
      <webElementGuid>b23debb5-e3fc-4fce-8791-b7ab10670e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template-default page page-id-187 wp-custom-logo ehf-template-hello-elementor ehf-stylesheet-hello-elementor elementor-default elementor-template-full-width elementor-kit-7 elementor-page elementor-page-187 elementor-page-422 e--ua-blink e--ua-chrome e--ua-webkit&quot;]/div[@class=&quot;elementor elementor-187&quot;]/div[@class=&quot;elementor-element elementor-element-6e258e77 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-330e3c9 elementor-hidden-mobile elementor-search-form--skin-classic elementor-search-form--button-type-icon elementor-search-form--icon-search elementor-widget elementor-widget-search-form&quot;]/div[@class=&quot;elementor-widget-container&quot;]/search[1]/form[@class=&quot;elementor-search-form&quot;]/div[@class=&quot;elementor-search-form__container&quot;]/button[@class=&quot;elementor-search-form__submit&quot;]/div[@class=&quot;e-font-icon-svg-container&quot;]</value>
      <webElementGuid>95613b2f-42f2-48f4-b5c5-ff94801e1b19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[1]</value>
      <webElementGuid>a1f6f2ff-5b2b-4f2c-9b5a-21c79bf09c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[8]/following::div[6]</value>
      <webElementGuid>24a4cc92-43f1-4058-8b50-a74caafcc32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::div[1]</value>
      <webElementGuid>33055817-6b7f-4fce-aa8c-e63e0a3e215c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLATO Panel Talks: Taking on Enterprise Testing'])[1]/preceding::div[2]</value>
      <webElementGuid>657a500d-fd8e-4d3a-82b8-8224d0a52b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>36e28be6-42d0-4f0e-9e1a-55726cd92f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
