<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_s</name>
   <tag></tag>
   <elementGuidId>dec4749e-1eab-4a8b-9e28-ff36be3a26be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='elementor-search-form-330e3c9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#elementor-search-form-330e3c9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ea09a01-2581-4add-bf72-45ab4319594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>elementor-search-form-330e3c9</value>
      <webElementGuid>090c948e-046f-458e-a33a-2c3a31f5c7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>f0036080-2a1d-4df6-83ac-391b9af36284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-search-form__input</value>
      <webElementGuid>5e3af176-7aba-4947-b73d-8c85c015e9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>03d6b79c-dc84-4340-a1d3-00fa3208e1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>0529e21e-b7b9-4812-886e-66f9e80c06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;elementor-search-form-330e3c9&quot;)</value>
      <webElementGuid>d9ee4052-d418-4578-b6a2-4f622618e185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='elementor-search-form-330e3c9']</value>
      <webElementGuid>292689ef-954e-4b42-8559-861903cf99e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ae090ec4-f092-4578-bf95-64c4261d916b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'elementor-search-form-330e3c9' and @placeholder = 'Search...' and @type = 'search' and @name = 's']</value>
      <webElementGuid>82dcbaf1-a6dd-4fcd-a6fc-ff2be3def660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
