<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter Phone</name>
   <tag></tag>
   <elementGuidId>e751c0e2-351e-4a0c-b5fd-8260b842f13d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tel-346']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tel-346&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54fa3b31-a049-4cbb-8e81-205cae8034f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-number wpcf7-validates-as-required wpcf7-validates-as-number</value>
      <webElementGuid>634c2e35-7874-4c26-955d-89e9e6462e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>abbec3b4-592b-4bef-adaa-c71b2e5bc961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7783e94c-c73e-44b2-aba4-ae1bc97e5b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1031ca5a-1a1b-4955-8b83-46d286abe55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9b27236b-2d9c-47ba-a713-5c6763a352c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel-346</value>
      <webElementGuid>bd5ddb5e-26ac-4951-b02f-eeb9c5ef099c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1199-p221-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[8]/b[1]/font[1]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-number wpcf7-validates-as-required wpcf7-validates-as-number&quot;]</value>
      <webElementGuid>818e22e0-071f-4b41-aa6f-7d6e1e1a42c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tel-346']</value>
      <webElementGuid>98a1c22d-993f-4098-b182-bf5009eb9178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1199-p221-o1']/form/div[2]/p[8]/b/font/span/input</value>
      <webElementGuid>368b0369-e231-478e-9c11-24aa190c6dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/b/font/span/input</value>
      <webElementGuid>8be5cb13-1ea1-4d46-9466-537448c03998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'tel-346']</value>
      <webElementGuid>06f5e74f-a402-4361-85d6-65933c1d27e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
