<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select Amount Range</name>
   <tag></tag>
   <elementGuidId>7ad0bb0e-4f3a-4201-b270-8a0c9d4373e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='menu-559']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;menu-559&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>58f571e0-3e70-43d7-ba37-973c98fb19e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-select wpcf7-validates-as-required</value>
      <webElementGuid>9c022e9c-2010-44db-b90e-5f5918fefc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad2cd5ef-4410-4dbf-bd4b-dedb10ef0ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b9ac5de3-f847-4e7f-a252-4b1f1d9e4eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu-559</value>
      <webElementGuid>73d0fcbb-3345-4cc1-8c8b-40de3c3dd23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined</value>
      <webElementGuid>20a7d727-432b-49a5-aaa6-5aba9dcc9108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1107-p195-o1&quot;)/form[@class=&quot;wpcf7-form init&quot;]/div[@class=&quot;whole-form&quot;]/p[10]/span[@class=&quot;wpcf7-form-control-wrap&quot;]/select[@class=&quot;wpcf7-form-control wpcf7-select wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>e121dc93-82c9-4275-bdb7-256d0e9e4873</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='menu-559']</value>
      <webElementGuid>8d179d89-c4f8-4dcd-b9d6-4ee0d3bb7048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1107-p195-o1']/form/div[2]/p[10]/span/select</value>
      <webElementGuid>c8a4f824-f0da-4845-8551-35eb530e79ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>427ab6be-fe98-43cd-a804-d7fccfb50f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work With Us'])[7]/preceding::select[1]</value>
      <webElementGuid>4ae1b861-1925-4ddb-aeb3-cffb030a166b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL BUSINESS INQUIRIES'])[1]/preceding::select[1]</value>
      <webElementGuid>47ce599b-235c-4c9a-8469-4713a3e427f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/select</value>
      <webElementGuid>174043ad-492f-44f2-8c1b-eff954bd4074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'menu-559' and (text() = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined' or . = 'Under $10,000$10,001 - $50,000$50,001 - $250,000$250,000+Undetermined')]</value>
      <webElementGuid>306ed310-b93f-432e-a09d-c77ab504f9f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
